export const FETCH_SINGLE_PLANE_INFO = 'FETCH_SINGLE_PLANE_INFO'
export const SET_SINGLE_PLANE_INFO = 'SET_SINGLE_PLANE_INFO'
export const FETCH_SINGLE_PLANE_LOGO = 'FETCH_SINGLE_PLANE_LOGO'
export const SET_SINGLE_PLANE_LOGO = 'SET_SINGLE_PLANE_LOGO'
